### ISSUE TITLE
shadows template parameter

### ISSUE THREAD

**Issue by AshishKarel** [AndrewB330/EuclideanMST#1]
Hello andrew,

Tried to run your code but i faced this issue.

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
$ g++ main.cpp -o binary
In file included from emst.h:2:0,
                 from main.cpp:9:
model.h:21:14: error: declaration of template parameter ‘DIM’ shadows template parameter
     template<size_t DIM>
              ^~~~~~
model.h:9:10: note: template parameter ‘DIM’ declared here
 template<size_t DIM>
          ^~~~~~
model.h:69:14: error: declaration of template parameter ‘DIM’ shadows template parameter
     template<size_t DIM>
              ^~~~~~
model.h:47:10: note: template parameter ‘DIM’ declared here
 template<size_t DIM>
          ^~~~~~
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

**Comment by AndrewB330** [comment]
Fixed, thanks for the report
